### ISSUE TITLE
Changing the font of the logo name

### ISSUE THREAD

**Issue by Neha00011** [developer-diganta/Dino#117] opened 2023-01-25 08:37 UTC
I want to change the font of heading .Can you please assign this issue to me under SWOC'23?

![Screenshot (56)](https://user-images.githubusercontent.com/112271756/214516190-a832c2b2-ba82-400a-865c-401c8215bd03.png)

**Comment by developer-diganta** [comment] 2023-01-25 18:26
@Neha00011 Can you please elaborate it a bit more? Since the logo was designed with references to dyslexic friendly fonts, but we can always improve. Do suggest what you are thinking of changing.

**Comment by Neha00011** [comment] 2023-01-26 15:54
I want to remove! Mark from the name as I think it is little bit weird
looking and also don't size of the heading can be increased a little bit.
It will look better.

**Comment by developer-diganta** [comment] 2023-01-26 18:46
You can change the size of the header. I have the design files for the logo! I'll change it! Thanks for the suggestion!

**Comment by SonamB11** [comment] 2023-01-28 12:15
I want to take this issue under SWOC 2023.Please assign this to me.

**Comment by Neha00011** [comment] 2023-01-28 12:22
Thanks for assigning the issue to me

**Closed** 2023-01-29 16:53 UTC
Labels: Beginner, SWOC

**Comment by Neha00011** [comment] 2023-01-29 17:19
Thank you!
