### ISSUE TITLE
Adding a Favicon 

### ISSUE THREAD

**Issue by AnkitMajee** [developer-diganta/Dino#8] opened 2022-12-30 12:20 UTC
### Subject of the issue
Favicon 

### Your environment

>**The site will have a icon like this**

![image](https://user-images.githubusercontent.com/76817118/210069295-7973c18d-e2a6-452c-bdcf-27b9cc230a88.png)
![image](https://user-images.githubusercontent.com/76817118/210069331-bc14946f-5bf3-490c-b4d9-8d49b87a1fa5.png)

### Steps to reproduce
Will Design a logo similar to that of Dino!

### Expected behaviour
Get a icon on the site

### Actual behaviour
Display the icon on the site

**Comment by AnkitMajee** [comment] 2022-12-30 12:21
SWOC S3 Contributor

**Comment by developer-diganta** [comment] 2022-12-30 12:25
Thanks for the idea! You can add this on the documentation for now. Once a website is there, we can add it there too.

**Comment by AnkitMajee** [comment] 2022-12-30 12:42
When should i make the pull request after 1 January or now 

- I will make the Design and will comment it in this chat whatever change you like you can tell me
- Then i will add and push the file

**Comment by Shubhodaya** [comment] 2022-12-30 13:03
Hey! Can I work on adding favicon once the site is done.

**Comment by Durgesh4993** [comment] 2022-12-30 13:35
Could you assign this work to me

**Comment by developer-diganta** [comment] 2022-12-30 16:59
@Shubhodaya @Durgesh4993 Currently since @AnkitMajee is already working on it, could you please check some other issues?

**Comment by SattyamSamania** [comment] 2023-01-28 09:50
Hey @developer-diganta If the issue is still open can I work on this?

**Comment by developer-diganta** [comment] 2023-01-29 08:39
@AnkitMajee are you working on it?

**Comment by AnkitMajee** [comment] 2023-01-29 12:16
I have already made the pull request and its been closed now

**Comment by developer-diganta** [comment] 2023-01-29 16:55
@AnkitMajee Sorry! I forgot about it.

**Closed by developer-diganta** 2023-01-29 16:55 UTC
Labels: Beginner
